spring:
  jpa:
    show-sql: true

  # 메세지 국제화 (스프링 부트용)
  # MessageSource 를 스프링 빈으로 등록하지 않고, 스프링 부트와 관련된 별도의 설정을 하지 않으면 'messages'라는 이름으로 기본 등록된다.
  # 따라서 'messages_en.properties', 'messages_ko.properties', 'messages.properties' 파일만 등록하면 자동 인식된다.
  messages:
    basename: messages,config.i18n.messages

logging:
  level:
    root: info  # 기본값 info
